# Sample Configuration

dataEventType: Asimov # {}
#llhStatFunction: "BarlowLLH"
#llhStatFunction: "BarlowLLH_OA2020_Bad"
llhStatFunction: "BarlowLLH_Fix_Weight"
#llhStatFunction: "EffLLH"
#llhStatFunction: "PoissonLLH"

fitSampleList:


  ##########################
  # FHC
  ##########################

  - name: "FHC FGD1 #nu_{#mu} CC 0#pi 0p 0#gamma" # kFGD1NuMuCC0Pi0ProtonsNoPhoton or FGD1_numuCC_0pi_0_protons_no_photon (detector)
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCC0Pi_0p.txt"
    selectionCuts: "SelectedSample == 7" 
    dataSets: [ "ND280" ]

  - name: "FHC FGD1 #nu_{#mu} CC 0#pi Np 0#gamma" # kFGD1NuMuCC0PiNProtonsNoPhoton or FGD1_numuCC_0pi_N_protons_no_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCC0Pi_Np.txt"
    selectionCuts: "SelectedSample == 8" 
    dataSets: [ "ND280" ]

  - name: "FHC FGD1 #nu_{#mu} CC 1#pi 0#gamma" # kFGD1NuMuCC1PiNoPhoton or FGD1_numuCC_1pi_no_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCC1Pi.txt"
    selectionCuts: "SelectedSample == 10" 
    dataSets: [ "ND280" ]

  - name: "FHC FGD1 #nu_{#mu} CC Other 0#gamma" # kFGD1NuMuCCOtherNoPhoton or FGD1_numuCC_other_no_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCCOth.txt"
    selectionCuts: "SelectedSample == 12" 
    dataSets: [ "ND280" ]

  - name: "FHC FGD1 #nu_{#mu} CC #gamma" # kFGD1NuMuCCPhoton or FGD1_numuCC_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCCPhoton.txt"
    selectionCuts: "SelectedSample == 13" 
    dataSets: [ "ND280" ]


  - name: "FHC FGD2 #nu_{#mu} CC 0#pi 0p 0#gamma" # kFGD2NuMuCC0Pi0ProtonsNoPhoton or FGD2_numuCC_0pi_0_protons_no_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCC0Pi_0p.txt"
    selectionCuts: "SelectedSample == 31" 
    dataSets: [ "ND280" ]

  - name: "FHC FGD2 #nu_{#mu} CC 0#pi Np 0#gamma" # kFGD2NuMuCC0PiNProtonsNoPhoton or FGD2_numuCC_0pi_N_protons_no_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCC0Pi_Np.txt"
    selectionCuts: "SelectedSample == 32" 
    dataSets: [ "ND280" ]

  - name: "FHC FGD2 #nu_{#mu} CC 1#pi 0#gamma" # kFGD2NuMuCC1PiNoPhoton or FGD2_numuCC_1pi_no_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCC1Pi.txt"
    selectionCuts: "SelectedSample == 34" 
    dataSets: [ "ND280" ]

  - name: "FHC FGD2 #nu_{#mu} CC Other 0#gamma" # kFGD2NuMuCCOtherNoPhoton or FGD2_numuCC_other_no_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCCOth.txt"
    selectionCuts: "SelectedSample == 36" 
    dataSets: [ "ND280" ]

  - name: "FHC FGD2 #nu_{#mu} CC #gamma" # kFGD2NuMuCCPhoton or FGD2_numuCC_photon
    isEnabled: true
    binning: "./inputs/samples/binnings/FHCNumuCCPhoton.txt"
    selectionCuts: "SelectedSample == 37" 
    dataSets: [ "ND280" ]




  ##########################
  # RHC - NUMU BKG
  ##########################

  - name: "RHC FGD1 Anti #nu_{#mu} CC 0#pi"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCANumuCC0Pi.txt"
    selectionCuts: "SelectedSample == 59" # FGD1 NuMuBkg CC0pi in AntiNu Mode kFGD1AntiNuMuCC0Pi
    dataSets: [ "ND280" ]

  - name: "RHC FGD1 Anti #nu_{#mu} CC 1#pi"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCANumuCC1Pi.txt"
    selectionCuts: "SelectedSample == 60" # FGD1 NuMuBkg CC1pi in AntiNu Mode kFGD1AntiNuMuCC1Pi
    dataSets: [ "ND280" ]

  - name: "RHC FGD1 Anti #nu_{#mu} CC Other"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCANumuCCOth.txt"
    selectionCuts: "SelectedSample == 61" # FGD1 NuMuBkg CCother in AntiNu Mode kFGD1AntiNuMuCCOther
    dataSets: [ "ND280" ]

  - name: "RHC FGD2 Anti #nu_{#mu} CC 0#pi"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCANumuCC0Pi.txt"
    selectionCuts: "SelectedSample == 65" # FGD2 NuMuBkg CC0pi in AntiNu Mode
    dataSets: [ "ND280" ]

  - name: "RHC FGD2 Anti #nu_{#mu} CC 1#pi"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCANumuCC1Pi.txt"
    selectionCuts: "SelectedSample == 66" # FGD2 NuMuBkg CC1pi in AntiNu Mode kFGD2AntiNuMuCC1Pi
    dataSets: [ "ND280" ]

  - name: "RHC FGD2 Anti #nu_{#mu} CC Other"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCANumuCCOth.txt"
    selectionCuts: "SelectedSample == 67" # FGD2 NuMuBkg CCother in AntiNu Mode kFGD2AntiNuMuCCOther
    dataSets: [ "ND280" ]

  - name: "RHC FGD1 #nu_{#mu} (background) CC 0#pi in AntiNu_Mode" #                        
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCNumuCC0Pi.txt"
    selectionCuts: "SelectedSample == 71" # FGD1 NuMuBkg CC0pi in AntiNu Mode kFGD1NuMuBkgInAntiNuModeCC0Pi
    dataSets: [ "ND280" ]

  - name: "RHC FGD1 #nu_{#mu} (background) CC 1#pi in AntiNu_Mode" 
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCNumuCC1Pi.txt"
    selectionCuts: "SelectedSample == 72" # FGD1 NuMuBkg CC1pi in AntiNu Mode kFGD1NuMuBkgInAntiNuModeCC1Pi
    dataSets: [ "ND280" ]

  - name: "RHC FGD1 #nu_{#mu} (background) CC Other in AntiNu_Mode"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCNumuCCOth.txt"
    selectionCuts: "SelectedSample == 73" # FGD1 NuMuBkg CCother in AntiNu Mode kFGD1NuMuBkgInAntiNuModeCCOther
    dataSets: [ "ND280" ]


  - name: "RHC FGD2 #nu_{#mu} (background) CC 0#pi in AntiNu_Mode"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCNumuCC0Pi.txt"
    selectionCuts: "SelectedSample == 77" # FGD2 NuMuBkg CC0pi in AntiNu Mode kFGD2NuMuBkgInAntiNuModeCC0Pi
    dataSets: [ "ND280" ]

  - name: "RHC FGD2 #nu_{#mu} (background) CC 1#pi  in AntiNu_Mode"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCNumuCC1Pi.txt"
    selectionCuts: "SelectedSample == 78" # FGD2 NuMuBkg CC1pi in AntiNu Mode kFGD2NuMuBkgInAntiNuModeCC1Pi
    dataSets: [ "ND280" ]

  - name: "RHC FGD2 #nu_{#mu} (background) CC Other  in AntiNu_Mode"
    isEnabled: true
    binning: "./inputs/samples/binnings/RHCNumuCCOth.txt"
    selectionCuts: "SelectedSample == 79" # FGD2 NuMuBkg CCother in AntiNu Mode kFGD2NuMuBkgInAntiNuModeCCOther
    dataSets: [ "ND280" ]

#SampleId::SampleEnum::kFGD1NuMuCC0Pi0ProtonsNoPhoton -> 7
#SampleId::SampleEnum::kFGD1NuMuCC0PiNProtonsNoPhoton -> 8
#SampleId::SampleEnum::kFGD1NuMuCC1PiNoPhoton -> 10
#SampleId::SampleEnum::kFGD1NuMuCCOtherNoPhoton -> 12
#SampleId::SampleEnum::kFGD1NuMuCCPhoton -> 13
#SampleId::SampleEnum::kFGD2NuMuCC0Pi0ProtonsNoPhoton -> 31
#SampleId::SampleEnum::kFGD2NuMuCC0PiNProtonsNoPhoton -> 32
#SampleId::SampleEnum::kFGD2NuMuCC1PiNoPhoton -> 34
#SampleId::SampleEnum::kFGD2NuMuCCOtherNoPhoton -> 36
#SampleId::SampleEnum::kFGD2NuMuCCPhoton -> 37
