generateSamplePlots: true
generateOneSigmaPlots: false # can be enabled with --one-sigma
scanParameters: false # can be triggered with --scan

# Pushing the parameter away from the minimum allow Minuit to better scan the area
throwMcBeforeFit: true
# Some fit parameter may have huge prior, no need to push everybody at 1sigma in average
# ThrowPar = ParPrior +  throwMcBeforeFitGain * randomGaus(0, 1sigma)
throwMcBeforeFitGain: 0.1
fit: true # can be disabled with -d

# false by default
restoreStepSizeBeforeHesse: true

fitterEngineConfig:

  fixGhostFitParameters: false
  ghostParameterDeltaChi2Threshold: 1E-4

  minimizerConfig:
    # https://root.cern.ch/download/minuit.pdf
    minimizer: "Minuit2"
    algorithm: "Migrad"
    errors: "Hesse"
    #    errors: "Minos"
    #likelihood: "BarlowLLHFixWeight"
    #likelihood: "Barlow"
    print_level: 2
    # Migrad: The default tolerance is 0.1, and the minimization will stop
    # when the estimated vertical distance to the minimum (EDM) is less
    # than 0.001*[tolerance]*UP (see SET ERR).
    # UP:
    # Minuit defines parameter errors as the change in parameter value required
    # to change the function value by UP. Normally, for chisquared fits
    # UP=1, and for negative log likelihood, UP=0.5
    #tolerance: 1E-4
    tolerance: 0.01
    #    tolerance: 0.1 # for debug
    strategy: 1
    max_iter: 100000
    max_fcn: 1E9

    useNormalizedFitSpace: false

  propagatorConfig:

    showEventBreakdown: true # default: true
    showEventBreakdownBeforePrior: true # default: false
    throwParameters: false

    dataSetList:            "./inputs/datasets/configDatasets.yaml"
    fitSampleSetConfig:     "./inputs/samples/configSamples_banff_v5.yaml"
    parameterSetListConfig: "./inputs/parameters/configParSet_banff_fin_v8.yaml"
    plotGeneratorConfig:    "./commonConfigPlotGenerator.yaml"

