#########################################
# OA 2021 inputs for ND fit
#########################################

fit: true # can be disabled with -d
generateSamplePlots: true
generateOneSigmaPlots: false # can be enabled with --one-sigma
scanParameters: false # can be triggered with --scan

outputFolder: "./output"
minGundamVersion: 1.4.5


fitterEngineConfig:

  monitorRefreshRateInMs: 5000

  # Fixing parameters that don't have any effect on the sample.
  # Sometimes Minuit has trouble computing the Hessian matrix (non-positive definite)
  # while too many parameters are
  fixGhostFitParameters: true
  # If the stat chi2 don't move over this value, the parameter will be fixed
  ghostParameterDeltaChi2Threshold: 0.01
  fixGhostEigenParmetersAfterFirstRejected: true

  # Apply gain on the determination of the step size for the fitter
  #  scaleParStepWithChi2Response: true # default :false. use 1 sigma instead
  #  parStepGain: 0.1

  # Throw (correlated) parameters before making the fit
  # This helps Minuit converge while doing an Asimov fit when too many fit parameters are involved
  # Pushing the parameter away from the minimum allow Minuit to better scan the area
  throwMcBeforeFit: false
  # Some fit parameter may have huge prior, no need to push everybody at 1sigma in average
  # ThrowPar = ParPrior +  throwMcBeforeFitGain * randomGaus(0, 1sigma)
  throwMcBeforeFitGain: 0.1

  # false by default
  restoreStepSizeBeforeHesse: false

  scanConfig: "./inputs/fitter/configScan.yaml"
  minimizerConfig: "./inputs/fitter/configMinimizer.yaml"

  propagatorConfig:

    showEventBreakdown: true # default: true
    showEventBreakdownBeforePrior: true # default: false
    throwParameters: false

    dataSetList:            "./inputs/datasets/configDatasets.yaml"
    fitSampleSetConfig:     "./inputs/samples/configSamples.yaml"
    parameterSetListConfig: "./inputs/parameters/configParSet.yaml"
    plotGeneratorConfig:    "./inputs/plots/configPlotGenerator.yaml"

