# https://root.cern.ch/doc/master/NumericalMinimization_8C.html
minimizer: "Minuit2"
algorithm: "Migrad"
#    algorithm: "Fumili2"

#    minimizer: "GSLMultiMin"
#    algorithm: "BFGS2"
#    algorithm: "ConjugateFR"

errors: "Hesse"
#    errors: "Minos"
enablePostFitErrorFit: true

# https://root.cern.ch/download/minuit.pdf
print_level: 2

# Migrad: The default tolerance is 0.1, and the minimization will stop
# when the estimated vertical distance to the minimum (EDM) is less
# than 0.001*[tolerance]*UP (see SET ERR).
# UP:
# Minuit defines parameter errors as the change in parameter value required
# to change the function value by UP. Normally, for chisquared fits
# UP=1, and for negative log likelihood, UP=0.5
tolerance: 1E-4 # 1E-4
#tolerance: 1E-2 # 1E-4
#    tolerance: 0.1 # for debug
strategy: 1 # used also in BANFF
max_iter: 100000
max_fcn: 1E9

# useNormalizedFitSpace: when true, every parameter is rescaled such as the
# prior mean value is set to 0 and the prior sigma is set to 1. This option
# can help Minuit to converge while some parameter may have very different scales.
# default: true
useNormalizedFitSpace: true