# ------------------------
# Dataset definitions
# ------------------------

- name: "ND280"
  isEnabled: true

  showSelectedEventCount: true

  selectedDataEntry: "Asimov" # default

  mc:
    tree: "sample_sum"
    selectionCutFormula: "passedPsyche * (!isConsecutiveIdenticalEvent) * (LocalEntry$ < 1000)"
#    selectionCutFormula: "( NVertexID == 1 ) * passedPsyche * (DetNomWeight > 0) * (FluxWeight[0] > 0) * (!isConsecutiveIdenticalEvent)"
#    nominalWeightFormula:
#      - "FluxWeight[0] * POTWeight * PileUpWeight"
#      - "(DetNomWeight > 10) ? 10: (DetNomWeight < 0 ? 0 : DetNomWeight)"
#      - "1 + ( TMath::Abs(ReactionCode) == 38 || TMath::Abs(ReactionCode) == 39 )"
    #    additionalLeavesStorage: [ "SelectedSample" ]
    overrideLeafDict: # originalVarName, otherLeafName[optionalArrayIndex]
      - { eventVar: "Pmu",            leafVar: "PmuCoulombCorrection" }
    filePathList:
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run2aMCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run2wMCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run3MCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run4aMCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run4wMCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run5MCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run6MCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run7MCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run8aMCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run8wMCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/run9MCsplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runFHCsand2aSplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runFHCsand2wSplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runFHCsand3Splines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runFHCsand4aSplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runFHCsand4wSplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runRHCsand5Splines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runRHCsand6Splines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runRHCsand7Splines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runFHCsand8aSplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runFHCsand8wSplines.root"
#      - "/sps/t2k/common/inputs/OA2021/ND280/MC/NonMirrored_Splines/v7_UpdatedKnots/WithExtraBranchesForGundam/runRHCsand9Splines.root"
      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2021/NDMC_psycheInfoAdded/ExtraBranchesForGundam/run4aMCsplines.root"
#      - "/Users/ablanche/Documents/Work/Output/results/gundam/common/OA2021/NDMC_psycheInfoAdded/ExtraBranchesForGundam/run5MCsplines.root"

  data:
    - name: "FDS"
      fromMc: true
      filePathList:
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run2air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run2water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run3air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run4air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run4water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run5water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run6air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run7water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run8air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run8water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run9water_v1.root"


