# ------------------------
# Dataset definitions
# ------------------------

- name: "ND280"
  isEnabled: true

  showSelectedEventCount: true

  selectedDataEntry: "Asimov" # default

  mc:
    tree: "sample_sum"
    selectionCutFormula: "passedPsyche * (!isConsecutiveIdenticalEvent)"
#    selectionCutFormula: "( NVertexID == 1 ) * passedPsyche * (DetNomWeight > 0) * (FluxWeight[0] > 0) * (!isConsecutiveIdenticalEvent)"
    nominalWeightFormula: "FluxWeight[0] * POTWeight * PileUpWeight * ( (DetNomWeight > 10) ? 10: (DetNomWeight < 0 ? 0 : DetNomWeight) ) * ( 1 + ( TMath::Abs(ReactionCode) == 38 || TMath::Abs(ReactionCode) == 39 ) )"
    #    additionalLeavesStorage: [ "SelectedSample" ]
    overrideLeafDict: # originalVarName, otherLeafName[optionalArrayIndex]
      - { eventVar: "Pmu",            leafVar: "PmuCoulombCorrection" }
    filePathList:
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run2aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run2wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run3MCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run4aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run4wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run5MCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run6MCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run7MCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run8aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run8wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/run9MCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runFHCsand2aSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runFHCsand2wSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runFHCsand3Splines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runFHCsand4aSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runFHCsand4wSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runRHCsand5Splines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runRHCsand6Splines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runRHCsand7Splines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runFHCsand8aSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runFHCsand8wSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/AsimovWithExtraBranchesForGundam/runRHCsand9Splines.root"

  data:
    - name: "FDS"
      fromMc: true
      filePathList:
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run2air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run2water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run3air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run4air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run4water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run5water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run6air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run7water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run8air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run8water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run9water_v1.root"


