# ------------------------
# Dataset definitions
# ------------------------

- name: "ND280"
  isEnabled: true

  showSelectedEventCount: true

  selectedDataEntry: "Asimov" # default

  mc:
    tree: "sample_sum"
    selectionCutFormula: "( NVertexID == 1 ) * passedPsyche * (DetNomWeight > 0) * (FluxWeight[0] > 0)"
    nominalWeightFormula: "FluxWeight[0] * POTWeight * PileUpWeight * DetNomWeight * ( 1 + ( TMath::Abs(ReactionCode) == 38 || TMath::Abs(ReactionCode) == 39 ) )"
    #    additionalLeavesStorage: [ "SelectedSample" ]
    filePathList:
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run2aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run2wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run3aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run4aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run4wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run5wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run6aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run7wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run8aMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run8wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/v3_RES_Eb_mirror_0/run9wMCsplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runFHCsand2aSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runFHCsand2wSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runFHCsand3Splines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runFHCsand4aSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runFHCsand4wSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runRHCsand5Splines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runRHCsand6Splines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runRHCsand7Splines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runFHCsand8aSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runFHCsand8wSplines.root"
      - "/sps/t2k/common/inputs/OA2021/ND280/Sand/PsycheIndependentSplines/runRHCsand9Splines.root"

  data:
    - name: "FDS"
      fromMc: true
      filePathList:
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run2air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run2water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run3air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run4air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run4water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run5water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run6air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run7water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run8air_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run8water_v1.root"
        - "/sps/t2k/common/inputs/OA2021/ND280/MC/mirrored_splines/FDSspline_v1/FDS_run9water_v1.root"


